// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOCnNj7DSdjg_EIDScVCBSDbq7n6klOYo',
    appId: '1:187538472244:web:ba41420fc5362c6fedf961',
    messagingSenderId: '187538472244',
    projectId: 'musik-7126c',
    authDomain: 'musik-7126c.firebaseapp.com',
    storageBucket: 'musik-7126c.appspot.com',
    measurementId: 'G-JVBV3NKR7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHSZ8TOA0es1hEDkYEpLS138PGfBOnOY8',
    appId: '1:187538472244:android:e165e37e27de86cfedf961',
    messagingSenderId: '187538472244',
    projectId: 'musik-7126c',
    storageBucket: 'musik-7126c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg2tLHj2hIKnQImFEWcgHrko8_S8dS39g',
    appId: '1:187538472244:ios:3d3d3df20000db3fedf961',
    messagingSenderId: '187538472244',
    projectId: 'musik-7126c',
    storageBucket: 'musik-7126c.appspot.com',
    iosClientId: '187538472244-ci3kj07230rm2lud5i14jamp7am550cn.apps.googleusercontent.com',
    iosBundleId: 'com.example.musik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg2tLHj2hIKnQImFEWcgHrko8_S8dS39g',
    appId: '1:187538472244:ios:3d3d3df20000db3fedf961',
    messagingSenderId: '187538472244',
    projectId: 'musik-7126c',
    storageBucket: 'musik-7126c.appspot.com',
    iosClientId: '187538472244-ci3kj07230rm2lud5i14jamp7am550cn.apps.googleusercontent.com',
    iosBundleId: 'com.example.musik',
  );
}
